=== sorinbiriescu/viator/app/schema/poi_multiple_schema.json
{
    "$id": "http://example.com/example.json",
    "type": "object",
    "definitions": {},
    "$schema": "http://json-schema.org/draft-06/schema#",
    "properties": {
        "total_results": {
            "$id": "/properties/total_results",
            "type": "integer",
            "title": "The Total_results Schema",
            "description": "An explanation about the purpose of this instance.",
            "default": 0,
            "examples": [
                10
            ]
        },
        "total_pages": {
            "$id": "/properties/total_pages",
            "type": "integer",
            "title": "The Total_pages Schema",
            "description": "An explanation about the purpose of this instance.",
            "default": 0,
            "examples": [
                1
            ]
        },
        "current_page": {
            "$id": "/properties/current_page",
            "type": "integer",
            "title": "The Current_page Schema",
            "description": "An explanation about the purpose of this instance.",
            "default": 0,
            "examples": [
                1
            ]
        },
        "result_geojson": {
            "$id": "/properties/result_geojson",
            "type": "object",
            "properties": {
                "type": {
                    "$id": "/properties/result_geojson/properties/type",
                    "type": "string",
                    "title": "The Type Schema",
                    "description": "An explanation about the purpose of this instance.",
                    "default": "",
                    "examples": [
                        "FeatureCollection"
                    ]
                },
                "features": {
                    "$id": "/properties/result_geojson/properties/features",
                    "type": "array",
                    "items": {
                        "$id": "/properties/result_geojson/properties/features/items",
                        "type": "object",
                        "properties": {
                            "type": {
                                "$id": "/properties/result_geojson/properties/features/items/properties/type",
                                "type": "string",
                                "title": "The Type Schema",
                                "description": "An explanation about the purpose of this instance.",
                                "default": "",
                                "examples": [
                                    "Feature"
                                ]
                            },
                            "geometry": {
                                "$id": "/properties/result_geojson/properties/features/items/properties/geometry",
                                "type": "object",
                                "properties": {
                                    "type": {
                                        "$id": "/properties/result_geojson/properties/features/items/properties/geometry/properties/type",
                                        "type": "string",
                                        "title": "The Type Schema",
                                        "description": "An explanation about the purpose of this instance.",
                                        "default": "",
                                        "examples": [
                                            "Point"
                                        ]
                                    },
                                    "coordinates": {
                                        "$id": "/properties/result_geojson/properties/features/items/properties/geometry/properties/coordinates",
                                        "type": "array",
                                        "items": {
                                            "$id": "/properties/result_geojson/properties/features/items/properties/geometry/properties/coordinates/items",
                                            "type": "number",
                                            "title": "The 0 Schema",
                                            "description": "An explanation about the purpose of this instance.",
                                            "default": 0,
                                            "examples": [
                                                5.731392860412598
                                            ]
                                        }
                                    }
                                }
                            },
                            "properties": {
                                "$id": "/properties/result_geojson/properties/features/items/properties/properties",
                                "type": "object",
                                "properties": {
                                    "name": {
                                        "$id": "/properties/result_geojson/properties/features/items/properties/properties/properties/name",
                                        "type": "string",
                                        "title": "The Name Schema",
                                        "description": "An explanation about the purpose of this instance.",
                                        "default": "",
                                        "examples": [
                                            "Musee de Grenoble"
                                        ]
                                    },
                                    "type": {
                                        "$id": "/properties/result_geojson/properties/features/items/properties/properties/properties/type",
                                        "type": "string",
                                        "title": "The Type Schema",
                                        "description": "An explanation about the purpose of this instance.",
                                        "default": "",
                                        "examples": [
                                            "Museum"
                                        ]
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}

=== sorinbiriescu/viator/app/schema/poi_multiple_example.json
{
    "total_results": 31,
    "total_pages": 4,
    "current_page": 1,
    "result_geojson": {
        "features": [{
            "geometry": {
                "coordinates": [5.7258889, 45.1904221],
                "type": "Point"
            },
            "properties": {
                "name": "Ibis Grenoble Centre",
                "type": "hotel"
            },
            "type": "Feature"
        }, {
            "geometry": {
                "coordinates": [5.7254788, 45.1891977],
                "type": "Point"
            },
            "properties": {
                "name": "H\u00f4tel d'Angleterre",
                "type": "hotel"
            },
            "type": "Feature"
        }, {
            "geometry": {
                "coordinates": [5.715705, 45.1911627],
                "type": "Point"
            },
            "properties": {
                "name": "H\u00f4tel Terminus",
                "type": "hotel"
            },
            "type": "Feature"
        }, {
            "geometry": {
                "coordinates": [5.7215297, 45.1874099],
                "type": "Point"
            },
            "properties": {
                "name": "H\u00f4tel Victoria",
                "type": "hotel"
            },
            "type": "Feature"
        }, {
            "geometry": {
                "coordinates": [5.7208, 45.1869457],
                "type": "Point"
            },
            "properties": {
                "name": "Splendid H\u00f4tel",
                "type": "hotel"
            },
            "type": "Feature"
        }, {
            "geometry": {
                "coordinates": [5.7199418, 45.1896195],
                "type": "Point"
            },
            "properties": {
                "name": "Touring H\u00f4tel",
                "type": "hotel"
            },
            "type": "Feature"
        }, {
            "geometry": {
                "coordinates": [5.7272545, 45.1903443],
                "type": "Point"
            },
            "properties": {
                "name": "H\u00f4tel de l'Europe",
                "type": "hotel"
            },
            "type": "Feature"
        }, {
            "geometry": {
                "coordinates": [5.7158276, 45.189528],
                "type": "Point"
            },
            "properties": {
                "name": "H\u00f4tel Aliz\u00e9",
                "type": "hotel"
            },
            "type": "Feature"
        }, {
            "geometry": {
                "coordinates": [5.7253515, 45.1909702],
                "type": "Point"
            },
            "properties": {
                "name": "H\u00f4tel Acacia",
                "type": "hotel"
            },
            "type": "Feature"
        }, {
            "geometry": {
                "coordinates": [5.7196593, 45.190826],
                "type": "Point"
            },
            "properties": {
                "name": "Ibis Styles",
                "type": "hotel"
            },
            "type": "Feature"
        }],
        "type": "FeatureCollection"
    }
}
